version: '3.3'
services:
    fin-dev:
        build:
          context: ../../
          dockerfile: ./docker/dev_frontend/Dockerfile
        env_file: 
          - ../../.dev.env 
        volumes:
            - ../../db_dev:/usr/src/app/db
            - ../../:/usr/src/app
            - /usr/src/app/frontend/node_modules
        network_mode: {YOUR_PROXY_NETWORK_HERE} 
        container_name: fin-dev
        ports:
            - '9028:9028' # Use NGINX config - SSL
        image: fin-dev